# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='name',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='students',
            name='admno',
        ),
        migrations.RemoveField(
            model_name='students',
            name='age',
        ),
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.EmailField(default=11, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='username',
            field=models.CharField(default=145, max_length=30),
            preserve_default=False,
        ),
    ]
