# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0003_projects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='name',
            new_name='Branch',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='admno',
            new_name='Projectyear',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='age',
        ),
        migrations.AddField(
            model_name='projects',
            name='Projectdescription',
            field=models.CharField(default='zzs', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='Projectname',
            field=models.CharField(default=54, max_length=30),
            preserve_default=False,
        ),
    ]
